const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "+94752631452"
const SESSION_ID = "PRABATH-MD~RvtikC6D#TI_BGBombjs3G8ibCybP7bTKB5_zfLaYRob2_0Mi0zY"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
